# ============================================================
# TV Workspace - 01-CreateTVUser.ps1
# Creates a separate Windows user account for TV sessions.
# Saves credentials so StartTV.bat can log in automatically.
# Run this ONCE during first-time setup.
# ============================================================

# ===== CONFIGURATION - you can change this =====
$TV_USERNAME = "TVUser"   # Name for the TV session account
# ===============================================

function Log($msg)  { Write-Host "  $msg" -ForegroundColor Cyan }
function OK($msg)   { Write-Host "  [OK] $msg" -ForegroundColor Green }
function Warn($msg) { Write-Host "  [!]  $msg" -ForegroundColor Yellow }
function Fail($msg) {
    Write-Host "  [X]  $msg" -ForegroundColor Red
    Write-Host ""
    Write-Host "  Press Enter to close..." -ForegroundColor Gray
    Read-Host | Out-Null
    exit 1
}

Write-Host ""
Write-Host "  TV Workspace - User Account Setup" -ForegroundColor White
Write-Host "  ===================================" -ForegroundColor DarkGray
Write-Host ""

# ---- Check existing user ----
$existingUser = Get-LocalUser -Name $TV_USERNAME -ErrorAction SilentlyContinue
if ($existingUser) {
    OK "User account '$TV_USERNAME' already exists"
    Warn "If you want to reset the password, delete the user first via:"
    Warn "  Settings > Accounts > Family & other users"
    Write-Host ""
} else {
    Log "Creating Windows user account: $TV_USERNAME"
    Write-Host ""
    Write-Host "  Choose a password for the TV account." -ForegroundColor White
    Write-Host "  This will be saved locally for auto-login." -ForegroundColor Gray
    Write-Host "  (You can use any password - it stays on this PC only)" -ForegroundColor Gray
    Write-Host ""

    $pass1 = Read-Host "  Enter password" -AsSecureString
    $pass2 = Read-Host "  Confirm password" -AsSecureString

    # Compare passwords
    $p1 = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
              [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($pass1))
    $p2 = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
              [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($pass2))

    if ($p1 -ne $p2) { Fail "Passwords do not match. Run this script again." }
    if ($p1.Length -lt 4) { Fail "Password too short. Use at least 4 characters." }

    try {
        New-LocalUser -Name $TV_USERNAME `
            -Password $pass1 `
            -FullName "TV Workspace" `
            -Description "Isolated account for TV/RDP session" `
            -PasswordNeverExpires $true `
            -ErrorAction Stop | Out-Null
        OK "User account '$TV_USERNAME' created"
    } catch {
        Fail "Could not create user: $_"
    }

    # Add to Users group (standard, non-admin)
    Add-LocalGroupMember -Group "Users" -Member $TV_USERNAME -ErrorAction SilentlyContinue

    # Add to Remote Desktop Users group (required for RDP login)
    Add-LocalGroupMember -Group "Remote Desktop Users" -Member $TV_USERNAME -ErrorAction SilentlyContinue
    OK "Added to 'Remote Desktop Users' group"
}

# ---- Read or re-enter password for config ----
Write-Host ""
Log "Saving credentials for auto-login..."
Write-Host ""
Write-Host "  Enter the password for '$TV_USERNAME' to save for auto-login." -ForegroundColor White
Write-Host "  (This is stored locally in tv-config.local.ps1 - never uploaded)" -ForegroundColor Gray
Write-Host ""

$savedPass = Read-Host "  Password for '$TV_USERNAME'" -AsSecureString
$savedPassPlain = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($savedPass))

# ---- Verify password works ----
Add-Type -AssemblyName System.DirectoryServices.AccountManagement
$ctx = New-Object System.DirectoryServices.AccountManagement.PrincipalContext(
    [System.DirectoryServices.AccountManagement.ContextType]::Machine)
$valid = $ctx.ValidateCredentials($TV_USERNAME, $savedPassPlain)

if (-not $valid) {
    Warn "Password did not match the account. Config saved anyway - double-check if login fails."
} else {
    OK "Password verified"
}

# ---- Save local config (gitignored) ----
$configPath = "$PSScriptRoot\tv-config.local.ps1"
@"
# TV Workspace local configuration
# This file is NOT tracked by git. Do not share it.
# Generated by 01-CreateTVUser.ps1

`$TV_USERNAME = "$TV_USERNAME"
`$TV_PASSWORD = "$savedPassPlain"
"@ | Out-File -FilePath $configPath -Encoding UTF8 -Force
OK "Saved to tv-config.local.ps1"

# ---- Save to Windows Credential Manager ----
& cmdkey /delete:"TERMSRV/127.0.0.2" 2>&1 | Out-Null
& cmdkey /generic:"TERMSRV/127.0.0.2" /user:"$env:COMPUTERNAME\$TV_USERNAME" /pass:"$savedPassPlain" 2>&1 | Out-Null
OK "Saved to Windows Credential Manager"

# ---- Set password never expires ----
Set-LocalUser -Name $TV_USERNAME -PasswordNeverExpires $true -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "  +---------------------------------------------+" -ForegroundColor Green
Write-Host "  |  Step 1 Complete!                           |" -ForegroundColor Green
Write-Host "  |  TV user account is ready.                  |" -ForegroundColor Green
Write-Host "  |                                             |" -ForegroundColor Green
Write-Host "  |  Next: Run 02-Setup.bat                     |" -ForegroundColor Green
Write-Host "  +---------------------------------------------+" -ForegroundColor Green
Write-Host ""
Write-Host "  Press Enter to close..." -ForegroundColor Gray
Read-Host | Out-Null
